service: psycopg2-lambda-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

layers:
  psycopg2-py37:
    description: "psycopg2 python postgresql client library."
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.7
    allowedAccounts:
      - '*'
    retain: true
