service: psycopg2-lambda-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  profile: jb

# you can overwrite defaults here
#  stage: dev
  region: eu-central-1

layers:
  psycopg2-py36:
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.6
    allowedAccounts:
      - '*'
    retain: true

